__version__ = '0.10'
__title__ = 'Flask-FormEncode'
__description__ = 'A form validation extension for Flask, adding CSRF by default and werkzeug FileUpload handling.'
__author__ = 'Steve Leonard'
__license__ = 'MIT'
